# Generated by Django 4.1.7 on 2023-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=500)),
                ('ph_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
